// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Meta": {
    "brand": "Noxaur",
    "title": "Noxaur — Websites for ambitious businesses in Kuwait",
    "description": "Premium websites, online stores and web apps designed and built in Kuwait."
  },
  "Home": {
    "eyebrow": "Kuwait · Web studio",
    "headline": "Websites that make your business look as serious as it is.",
    "subline": "Portfolios, online stores, landing pages and web apps — designed, built and launched with care."
  },
  "NotFound": {
    "title": "This page does not exist",
    "body": "The link may be outdated or mistyped.",
    "backHome": "Back to the homepage"
  },
  "Nav": {
    "home": "Home",
    "work": "Work",
    "services": "Services",
    "pricing": "Pricing",
    "about": "About",
    "contact": "Contact",
    "cta": "Start a project",
    "currency": "Currency",
    "toggleTheme": "Switch theme",
    "openMenu": "Open menu",
    "closeMenu": "Close menu"
  },
  "Footer": {
    "tagline": "A web studio in Kuwait building websites, stores and web apps that make businesses look established.",
    "work": "Work",
    "studio": "Studio",
    "services": "Services",
    "pricing": "Pricing",
    "about": "About",
    "contact": "Contact",
    "whatsapp": "WhatsApp",
    "whatsappText": "Hello Noxaur, I'd like to talk about a website.",
    "openNow": "Open now",
    "closedNow": "Closed now",
    "rights": "All rights reserved.",
    "madeIn": "Designed and built in Kuwait."
  }
};
export default messages;